language: go

go: 
  - 1.3.3
  - 1.4.2
  - 1.5.1
  - 1.6.2
  - 1.7.3

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN

before_install:
  - go get github.com/mattn/goveralls
