language: go

go: 
  - 1.3.3
  - 1.4.3
  - 1.5.4
  - 1.6.4
  - 1.7.6
  - 1.8.3

script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN

before_install:
  - go get github.com/mattn/goveralls
